/**
 * 常用韓國旅遊地名對照表
 * Open-Meteo 的 geocoding API 無法直接查到中文地名(例如「首爾」),
 * 因此提供一個在地對照表,把常見的中文譯名對應到英文地名,
 * 並限定 country_code=KR 讓搜尋結果優先落在韓國境內。
 */
export const KOREAN_PLACE_ALIASES: Record<string, string> = {
  首爾: 'Seoul',
  首爾市: 'Seoul',
  首爾特別市: 'Seoul',
  漢城: 'Seoul',
  釜山: 'Busan',
  釜山市: 'Busan',
  釜山廣域市: 'Busan',
  濟州: 'Jeju City',
  濟州島: 'Jeju City',
  濟州市: 'Jeju City',
  西歸浦: 'Seogwipo',
  西歸浦市: 'Seogwipo',
  仁川: 'Incheon',
  仁川廣域市: 'Incheon',
  大邱: 'Daegu',
  大邱廣域市: 'Daegu',
  大田: 'Daejeon',
  大田廣域市: 'Daejeon',
  光州: 'Gwangju',
  光州廣域市: 'Gwangju',
  蔚山: 'Ulsan',
  蔚山廣域市: 'Ulsan',
  京畿道: 'Suwon',
  江原道: 'Chuncheon',
  春川: 'Chuncheon',
  江陵: 'Gangneung',
  束草: 'Sokcho',
  平昌: 'Pyeongchang',
  全州: 'Jeonju',
  全州市: 'Jeonju',
  慶州: 'Gyeongju',
  慶州市: 'Gyeongju',
  木浦: 'Mokpo',
  順天: 'Suncheon',
  麗水: 'Yeosu',
  麗水市: 'Yeosu',
  昌原: 'Changwon',
  金海: 'Gimhae',
  安東: 'Andong',
  浦項: 'Pohang',
  高陽: 'Goyang',
  城南: 'Seongnam',
  水原: 'Suwon',
  龍仁: 'Yongin',
  安山: 'Ansan',
  富川: 'Bucheon',
  議政府: 'Uijeongbu',
  始興: 'Siheung',
  軍浦: 'Gunpo',
  果川: 'Gwacheon',
  河南: 'Hanam',
  光明: 'Gwangmyeong',
  九里: 'Guri',
  坡州: 'Paju',
  驪州: 'Yeoju',
  平澤: 'Pyeongtaek',
  南楊州: 'Namyangju',
  華城: 'Hwaseong',
  抱川: 'Pocheon',
  加平: 'Gapyeong',
  楊平: 'Yangpyeong',
  江華: 'Ganghwa',
  弘大: 'Seoul',
  弘益大學: 'Seoul',
  明洞: 'Seoul',
  江南: 'Seoul',
  弘大一帶: 'Seoul',
  清溪川: 'Seoul',
  景福宮: 'Seoul',
  北村韓屋村: 'Seoul',
  北村: 'Seoul',
  東大門: 'Seoul',
  南怡島: 'Chuncheon',
  南山: 'Seoul',
  塔石公園: 'Jeonju',
  城山日出峰: 'Seogwipo',
  漢拏山: 'Jeju City',
  漢拿山: 'Jeju City',
}
